-- SDKWork membership consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_membership_baseline.sql
-- Membership initialization tables (SQLite).
-- This repository is self-contained for local membership frontend/backend
-- integration. Order creation remains owned by sdkwork-order; this baseline
-- does not create commerce_order and seeds do not insert order rows.

-- 0. Local support tables required by membership catalog, entitlement, and
-- authenticated frontend flows.
CREATE TABLE IF NOT EXISTS commerce_product_spu (
    id              TEXT    NOT NULL,
    tenant_id       TEXT    NOT NULL,
    organization_id TEXT    NOT NULL DEFAULT '0',
    spu_no          TEXT    NOT NULL,
    name            TEXT,
    title           TEXT,
    sales_status    TEXT    NOT NULL DEFAULT 'active',
    status          TEXT    NOT NULL DEFAULT 'active',
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL,
    CONSTRAINT pk_commerce_product_spu PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_product_spu_tenant_no
    ON commerce_product_spu (tenant_id, organization_id, spu_no);

CREATE TABLE IF NOT EXISTS commerce_product_sku (
    id                    TEXT    NOT NULL,
    tenant_id             TEXT    NOT NULL,
    organization_id       TEXT    NOT NULL DEFAULT '0',
    spu_id                TEXT    NOT NULL,
    sku_no                TEXT    NOT NULL,
    name                  TEXT,
    title                 TEXT,
    price_amount          TEXT,
    original_price_amount TEXT,
    currency_code         TEXT,
    fulfillment_type      TEXT,
    inventory_tracking    TEXT,
    sales_status          TEXT    NOT NULL DEFAULT 'active',
    status                TEXT    NOT NULL DEFAULT 'active',
    spec_json             TEXT    NOT NULL DEFAULT '{}',
    created_at            TEXT    NOT NULL,
    updated_at            TEXT    NOT NULL,
    CONSTRAINT pk_commerce_product_sku PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_product_sku_tenant_no
    ON commerce_product_sku (tenant_id, organization_id, sku_no);
CREATE INDEX IF NOT EXISTS idx_commerce_product_sku_spu
    ON commerce_product_sku (tenant_id, spu_id, status);

CREATE TABLE IF NOT EXISTS membership_plan (
    id              TEXT    NOT NULL,
    uuid            TEXT,
    tenant_id       TEXT    NOT NULL,
    organization_id TEXT    NOT NULL DEFAULT '0',
    plan_no         TEXT    NOT NULL,
    plan_code       TEXT,
    name            TEXT    NOT NULL,
    rank            INTEGER NOT NULL DEFAULT 0,
    description     TEXT,
    status          TEXT    NOT NULL DEFAULT 'active',
    version         INTEGER NOT NULL DEFAULT 0,
    deleted_at      TEXT,
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL,
    CONSTRAINT pk_membership_plan PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_uuid
    ON membership_plan (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_tenant_no
    ON membership_plan (tenant_id, organization_id, plan_no);

CREATE TABLE IF NOT EXISTS membership_plan_version (
    id               TEXT    NOT NULL,
    uuid             TEXT,
    tenant_id        TEXT    NOT NULL,
    organization_id  TEXT    NOT NULL DEFAULT '0',
    plan_id          TEXT    NOT NULL,
    version_no       TEXT    NOT NULL,
    title            TEXT,
    description      TEXT,
    lifecycle_status TEXT    NOT NULL DEFAULT 'draft',
    effective_from   TEXT,
    effective_to     TEXT,
    published_at     TEXT,
    version          INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT    NOT NULL,
    updated_at       TEXT    NOT NULL,
    CONSTRAINT pk_membership_plan_version PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_version_uuid
    ON membership_plan_version (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_version_tenant_plan_no
    ON membership_plan_version (tenant_id, plan_id, version_no);
CREATE INDEX IF NOT EXISTS idx_membership_plan_version_published
    ON membership_plan_version (tenant_id, plan_id, lifecycle_status, version_no);

CREATE TABLE IF NOT EXISTS benefit_definition (
    id               TEXT    NOT NULL,
    uuid             TEXT,
    tenant_id        TEXT    NOT NULL,
    organization_id  TEXT    NOT NULL DEFAULT '0',
    benefit_code     TEXT    NOT NULL,
    name             TEXT    NOT NULL,
    benefit_type     TEXT    NOT NULL,
    value_unit       TEXT,
    measurement_type TEXT,
    description      TEXT,
    status           TEXT    NOT NULL DEFAULT 'active',
    version          INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT    NOT NULL,
    updated_at       TEXT    NOT NULL,
    CONSTRAINT pk_benefit_definition PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_benefit_definition_uuid
    ON benefit_definition (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_benefit_definition_tenant_code
    ON benefit_definition (tenant_id, organization_id, benefit_code);

CREATE TABLE IF NOT EXISTS membership_plan_benefit (
    id              TEXT    NOT NULL,
    tenant_id       TEXT    NOT NULL,
    organization_id TEXT    NOT NULL DEFAULT '0',
    plan_id         TEXT    NOT NULL,
    plan_version_id TEXT    NOT NULL,
    benefit_id      TEXT    NOT NULL,
    benefit_code    TEXT    NOT NULL,
    grant_quantity  TEXT    NOT NULL DEFAULT '0',
    grant_period    TEXT,
    reset_policy    TEXT,
    usage_policy    TEXT,
    sort_weight     INTEGER NOT NULL DEFAULT 0,
    status          TEXT    NOT NULL DEFAULT 'active',
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL,
    CONSTRAINT pk_membership_plan_benefit PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_membership_plan_benefit_plan
    ON membership_plan_benefit (tenant_id, plan_id, status, sort_weight);

CREATE TABLE IF NOT EXISTS membership_package_group (
    id              TEXT    NOT NULL,
    uuid            TEXT,
    tenant_id       TEXT    NOT NULL,
    organization_id TEXT    NOT NULL DEFAULT '0',
    external_id     INTEGER,
    group_no        TEXT    NOT NULL,
    name            TEXT    NOT NULL,
    description     TEXT,
    billing_cycle   TEXT,
    duration_days   INTEGER NOT NULL DEFAULT 0,
    display_channel TEXT,
    sort_weight     INTEGER NOT NULL DEFAULT 0,
    status          TEXT    NOT NULL DEFAULT 'active',
    version         INTEGER NOT NULL DEFAULT 0,
    deleted_at      TEXT,
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL,
    CONSTRAINT pk_membership_package_group PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_group_uuid
    ON membership_package_group (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_group_tenant_no
    ON membership_package_group (tenant_id, organization_id, group_no);

CREATE TABLE IF NOT EXISTS membership_package (
    id                    TEXT    NOT NULL,
    uuid                  TEXT,
    tenant_id             TEXT    NOT NULL,
    organization_id       TEXT    NOT NULL DEFAULT '0',
    external_id           INTEGER NOT NULL,
    package_no            TEXT    NOT NULL,
    package_group_id      TEXT    NOT NULL,
    plan_id               TEXT    NOT NULL,
    plan_version_id       TEXT,
    sku_id                TEXT,
    name                  TEXT    NOT NULL,
    description           TEXT,
    price_amount          TEXT    NOT NULL,
    original_price_amount TEXT,
    currency_code         TEXT    NOT NULL DEFAULT 'CNY',
    point_amount          INTEGER NOT NULL DEFAULT 0,
    duration_days         INTEGER NOT NULL,
    recurrence_cycle      TEXT,
    sort_weight           INTEGER NOT NULL DEFAULT 0,
    recommended           INTEGER NOT NULL DEFAULT 0,
    status                TEXT    NOT NULL DEFAULT 'active',
    starts_at             TEXT,
    ends_at               TEXT,
    tags                  TEXT    NOT NULL DEFAULT '[]',
    version               INTEGER NOT NULL DEFAULT 0,
    deleted_at            TEXT,
    created_at            TEXT    NOT NULL,
    updated_at            TEXT    NOT NULL,
    CONSTRAINT pk_membership_package PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_uuid
    ON membership_package (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_tenant_no
    ON membership_package (tenant_id, organization_id, package_no);
CREATE INDEX IF NOT EXISTS idx_membership_package_external_id
    ON membership_package (tenant_id, organization_id, external_id);

CREATE TABLE IF NOT EXISTS membership_subscription (
    id                       TEXT    NOT NULL,
    uuid                     TEXT,
    tenant_id                TEXT    NOT NULL,
    organization_id          TEXT    NOT NULL DEFAULT '0',
    subscription_no          TEXT    NOT NULL,
    subject_type             TEXT    NOT NULL,
    subject_id               TEXT    NOT NULL,
    owner_user_id            TEXT    NOT NULL,
    plan_id                  TEXT    NOT NULL,
    plan_version_id          TEXT,
    package_id               TEXT,
    current_period_id        TEXT,
    source_order_id          TEXT,
    status                   TEXT    NOT NULL DEFAULT 'pending',
    starts_at                TEXT    NOT NULL,
    expires_at               TEXT    NOT NULL,
    grace_until              TEXT,
    cancel_at_period_end     INTEGER NOT NULL DEFAULT 0,
    auto_renew               INTEGER NOT NULL DEFAULT 0,
    growth_value             INTEGER NOT NULL DEFAULT 0,
    request_no               TEXT,
    idempotency_key          TEXT,
    version                  INTEGER NOT NULL DEFAULT 0,
    created_at               TEXT    NOT NULL,
    updated_at               TEXT    NOT NULL,
    CONSTRAINT pk_membership_subscription PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_subscription_uuid
    ON membership_subscription (uuid);
CREATE INDEX IF NOT EXISTS idx_membership_subscription_idempotency
    ON membership_subscription (tenant_id, owner_user_id, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_membership_subscription_order
    ON membership_subscription (tenant_id, source_order_id);

CREATE TABLE IF NOT EXISTS membership_period (
    id                       TEXT    NOT NULL,
    uuid                     TEXT,
    tenant_id                TEXT    NOT NULL,
    organization_id          TEXT    NOT NULL DEFAULT '0',
    period_no                TEXT    NOT NULL,
    subscription_id          TEXT    NOT NULL,
    subject_type             TEXT    NOT NULL,
    subject_id               TEXT    NOT NULL,
    plan_id                  TEXT    NOT NULL,
    plan_version_id          TEXT,
    starts_at                TEXT    NOT NULL,
    ends_at                  TEXT    NOT NULL,
    status                   TEXT    NOT NULL,
    source_order_id          TEXT,
    request_no               TEXT,
    idempotency_key          TEXT,
    created_at               TEXT    NOT NULL,
    updated_at               TEXT    NOT NULL,
    CONSTRAINT pk_membership_period PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_period_uuid
    ON membership_period (uuid);
CREATE INDEX IF NOT EXISTS idx_membership_period_subscription
    ON membership_period (tenant_id, subscription_id, starts_at);

CREATE TABLE IF NOT EXISTS entitlement_account (
    id              TEXT    NOT NULL,
    uuid            TEXT,
    tenant_id       TEXT    NOT NULL,
    organization_id TEXT    NOT NULL DEFAULT '0',
    account_no      TEXT    NOT NULL,
    benefit_id      TEXT    NOT NULL,
    subject_type    TEXT    NOT NULL,
    subject_id      TEXT    NOT NULL,
    total_granted   TEXT    NOT NULL DEFAULT '0',
    total_used      TEXT    NOT NULL DEFAULT '0',
    balance         TEXT    NOT NULL DEFAULT '0',
    status          TEXT    NOT NULL DEFAULT 'pending',
    expires_at      TEXT,
    version         INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL,
    CONSTRAINT pk_entitlement_account PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_entitlement_account_uuid
    ON entitlement_account (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_entitlement_account_subject_benefit
    ON entitlement_account (tenant_id, subject_type, subject_id, benefit_id);

CREATE TABLE IF NOT EXISTS entitlement_grant (
    id                 TEXT    NOT NULL,
    uuid               TEXT,
    tenant_id          TEXT    NOT NULL,
    organization_id    TEXT    NOT NULL DEFAULT '0',
    grant_no           TEXT    NOT NULL,
    benefit_id         TEXT    NOT NULL,
    subject_type       TEXT    NOT NULL,
    subject_id         TEXT    NOT NULL,
    source_type        TEXT    NOT NULL,
    source_id          TEXT    NOT NULL,
    grant_policy       TEXT,
    granted_quantity   TEXT    NOT NULL DEFAULT '0',
    status             TEXT    NOT NULL DEFAULT 'pending',
    starts_at          TEXT,
    expires_at         TEXT,
    request_no         TEXT,
    idempotency_key    TEXT,
    created_at         TEXT    NOT NULL,
    updated_at         TEXT    NOT NULL,
    CONSTRAINT pk_entitlement_grant PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_entitlement_grant_uuid
    ON entitlement_grant (uuid);

CREATE TABLE IF NOT EXISTS entitlement_ledger_entry (
    id              TEXT    NOT NULL,
    uuid            TEXT,
    tenant_id       TEXT    NOT NULL,
    organization_id TEXT    NOT NULL DEFAULT '0',
    ledger_no       TEXT    NOT NULL,
    account_id      TEXT    NOT NULL,
    grant_id        TEXT,
    benefit_id      TEXT    NOT NULL,
    subject_type    TEXT    NOT NULL,
    subject_id      TEXT    NOT NULL,
    direction       TEXT    NOT NULL,
    amount          TEXT    NOT NULL,
    balance_after   TEXT    NOT NULL,
    business_type   TEXT    NOT NULL,
    source_type     TEXT    NOT NULL,
    source_id       TEXT    NOT NULL,
    request_no      TEXT,
    idempotency_key TEXT,
    occurred_at     TEXT    NOT NULL,
    created_at      TEXT    NOT NULL,
    CONSTRAINT pk_entitlement_ledger_entry PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_entitlement_ledger_uuid
    ON entitlement_ledger_entry (uuid);

CREATE TABLE IF NOT EXISTS commerce_account (
    id               BIGINT  NOT NULL,
    uuid             TEXT    NOT NULL,
    tenant_id        BIGINT  NOT NULL,
    organization_id  BIGINT  NOT NULL DEFAULT 0,
    owner_type       TEXT    NOT NULL DEFAULT 'USER',
    owner_id         BIGINT  NOT NULL,
    asset_code       TEXT    NOT NULL,
    currency_code    TEXT    NOT NULL,
    account_purpose  TEXT    NOT NULL DEFAULT 'GENERAL',
    available_amount BIGINT  NOT NULL DEFAULT 0,
    frozen_amount    BIGINT  NOT NULL DEFAULT 0,
    pending_amount   BIGINT  NOT NULL DEFAULT 0,
    status           INTEGER NOT NULL DEFAULT 1,
    version          BIGINT  NOT NULL DEFAULT 0,
    closed_at        TEXT,
    created_at       TEXT    NOT NULL,
    updated_at       TEXT    NOT NULL,
    CONSTRAINT pk_commerce_account PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_owner_asset UNIQUE (
        tenant_id, organization_id, owner_type, owner_id,
        asset_code, currency_code, account_purpose
    )
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_tenant_owner
    ON commerce_account (tenant_id, organization_id, owner_type, owner_id, asset_code);

CREATE TABLE IF NOT EXISTS commerce_account_ledger (
    id                     BIGINT NOT NULL,
    uuid                   TEXT   NOT NULL,
    tenant_id              BIGINT NOT NULL,
    organization_id        BIGINT NOT NULL DEFAULT 0,
    account_id             BIGINT NOT NULL,
    journal_id             BIGINT,
    owner_type             TEXT   NOT NULL,
    owner_id               BIGINT NOT NULL,
    asset_code             TEXT   NOT NULL,
    currency_code          TEXT   NOT NULL,
    ledger_type            TEXT   NOT NULL DEFAULT 'AVAILABLE',
    entry_type             TEXT   NOT NULL,
    direction              TEXT   NOT NULL,
    amount                 BIGINT NOT NULL,
    balance_before         BIGINT NOT NULL,
    balance_after          BIGINT NOT NULL,
    business_type          TEXT   NOT NULL,
    business_no            TEXT   NOT NULL,
    request_no             TEXT   NOT NULL,
    idempotency_key        TEXT   NOT NULL,
    source_type            TEXT,
    source_id              BIGINT,
    hold_id                BIGINT,
    transfer_id            BIGINT,
    exchange_snapshot_id   BIGINT,
    settlement_snapshot_id BIGINT,
    reversed_ledger_id     BIGINT,
    reference_no           TEXT,
    remark                 TEXT,
    metadata_json          TEXT   NOT NULL DEFAULT '{}',
    trace_id               TEXT   NOT NULL,
    created_at             TEXT   NOT NULL,
    CONSTRAINT pk_commerce_account_ledger PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_ledger_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_ledger_business_no UNIQUE (tenant_id, business_no),
    CONSTRAINT uk_commerce_account_ledger_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_ledger_account_created
    ON commerce_account_ledger (tenant_id, account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_commerce_account_ledger_owner_created
    ON commerce_account_ledger (tenant_id, organization_id, owner_type, owner_id, asset_code, created_at);

-- 1. Daily reward tracking table
CREATE TABLE IF NOT EXISTS commerce_membership_daily_reward (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    user_id         INTEGER      NOT NULL,
    reward_date     TEXT         NOT NULL,
    reward_points   INTEGER      NOT NULL DEFAULT 0,
    consecutive_days INTEGER     NOT NULL DEFAULT 1,
    total_days      INTEGER      NOT NULL DEFAULT 1,
    status          TEXT         NOT NULL DEFAULT 'claimed',
    idempotency_key TEXT,
    created_at      TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version         INTEGER      NOT NULL DEFAULT 0,
    updated_at      TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_commerce_membership_daily_reward PRIMARY KEY (id),
    CONSTRAINT chk_daily_reward_points CHECK (reward_points >= 0),
    CONSTRAINT chk_daily_reward_consecutive CHECK (consecutive_days >= 1),
    CONSTRAINT chk_daily_reward_status CHECK (status IN ('claimed', 'revoked'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_uuid
    ON commerce_membership_daily_reward (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_user_date
    ON commerce_membership_daily_reward (tenant_id, user_id, reward_date);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_idempotency
    ON commerce_membership_daily_reward (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_daily_reward_user_recent
    ON commerce_membership_daily_reward (tenant_id, user_id, reward_date DESC, id DESC);

-- 2. Privilege usage tracking table
CREATE TABLE IF NOT EXISTS commerce_membership_privilege_usage (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    user_id         INTEGER      NOT NULL,
    subscription_id INTEGER,
    benefit_code    TEXT         NOT NULL,
    period_start    TEXT         NOT NULL,
    period_end      TEXT         NOT NULL,
    used_count      INTEGER      NOT NULL DEFAULT 0,
    usage_limit     INTEGER      NOT NULL DEFAULT 0,
    last_used_at    TEXT,
    version         INTEGER      NOT NULL DEFAULT 0,
    created_at      TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_commerce_membership_privilege_usage PRIMARY KEY (id),
    CONSTRAINT chk_priv_usage_used CHECK (used_count >= 0),
    CONSTRAINT chk_priv_usage_limit CHECK (usage_limit >= 0),
    CONSTRAINT chk_priv_usage_period CHECK (period_end >= period_start)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_privilege_usage_uuid
    ON commerce_membership_privilege_usage (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_privilege_usage_unique
    ON commerce_membership_privilege_usage (tenant_id, user_id, benefit_code, period_start);
CREATE INDEX IF NOT EXISTS idx_priv_usage_user_period
    ON commerce_membership_privilege_usage (tenant_id, user_id, period_end);
CREATE INDEX IF NOT EXISTS idx_priv_usage_subscription
    ON commerce_membership_privilege_usage (subscription_id, created_at DESC);

-- 3. Membership change audit log (immutable)
CREATE TABLE IF NOT EXISTS commerce_membership_change_log (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    subscription_id INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    action          TEXT         NOT NULL,
    from_status     TEXT,
    to_status       TEXT,
    from_plan_id    TEXT,
    to_plan_id      TEXT,
    operator_id     INTEGER,
    operator_type   TEXT         DEFAULT 'system',
    reason          TEXT,
    metadata        TEXT,
    trace_id        TEXT,
    created_at      TEXT         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_commerce_membership_change_log PRIMARY KEY (id),
    CONSTRAINT chk_change_log_action CHECK (action IN (
        'activate', 'renew', 'upgrade', 'downgrade',
        'expire', 'cancel', 'grace', 'restore'
    )),
    CONSTRAINT chk_change_log_from_status CHECK (from_status IS NULL OR from_status IN ('active', 'expired', 'cancelled', 'grace_period', 'pending')),
    CONSTRAINT chk_change_log_to_status CHECK (to_status IS NULL OR to_status IN ('active', 'expired', 'cancelled', 'grace_period', 'pending'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_change_log_uuid
    ON commerce_membership_change_log (uuid);
CREATE INDEX IF NOT EXISTS idx_change_log_subscription
    ON commerce_membership_change_log (subscription_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_change_log_tenant_user
    ON commerce_membership_change_log (tenant_id, user_id, created_at DESC, id DESC);

-- 4. Add missing standard columns to existing membership tables
-- SQLite does not support ADD COLUMN IF NOT EXISTS, so we use a pragma check approach.
-- These are safe to run repeatedly; SQLite will error on duplicate columns which we ignore.

-- Add uuid, version, deleted_at to membership_plan
-- Note: In SQLite, we cannot easily check column existence in pure SQL.
-- The application layer handles this gracefully via error tolerance.

-- Add tags column to membership_package if missing
-- This is handled by the application layer's read_model fallback.

-- 5. Performance indexes
CREATE INDEX IF NOT EXISTS idx_membership_plan_tenant_status_rank
    ON membership_plan (tenant_id, organization_id, status, rank);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_tenant_status_sort
    ON membership_package_group (tenant_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_status_sort
    ON membership_package (package_group_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_tenant_status
    ON membership_package (tenant_id, organization_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_subscription_owner_status
    ON membership_subscription (tenant_id, owner_user_id, status, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_membership_plan_benefit_version_status
    ON membership_plan_benefit (plan_version_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_entitlement_account_subject_status
    ON entitlement_account (tenant_id, subject_id, status);

CREATE INDEX IF NOT EXISTS idx_entitlement_grant_source
    ON entitlement_grant (source_type, source_id, status);

CREATE INDEX IF NOT EXISTS idx_entitlement_ledger_account
    ON entitlement_ledger_entry (account_id, occurred_at DESC);

-- Note: SQLite does not support BEFORE UPDATE triggers that modify NEW safely
-- (AFTER UPDATE triggers cause recursion). updated_at is maintained by the
-- application layer (Rust repository UPDATE statements set updated_at explicitly).
