-- SDKWork membership consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_membership_baseline.sql
-- Membership extension tables migration (SQLite)
-- Adds membership-specific tables owned by sdkwork-membership capability.
-- Existing commerce domain tables are created by the commerce platform initial migration.

-- 1. Daily reward tracking table
CREATE TABLE IF NOT EXISTS commerce_membership_daily_reward (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    user_id         INTEGER      NOT NULL,
    reward_date     TEXT         NOT NULL,
    reward_points   INTEGER      NOT NULL DEFAULT 0,
    consecutive_days INTEGER     NOT NULL DEFAULT 1,
    total_days      INTEGER      NOT NULL DEFAULT 1,
    status          TEXT         NOT NULL DEFAULT 'claimed',
    idempotency_key TEXT,
    created_at      TEXT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_uuid
    ON commerce_membership_daily_reward (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_user_date
    ON commerce_membership_daily_reward (tenant_id, user_id, reward_date);
CREATE INDEX IF NOT EXISTS idx_daily_reward_user_recent
    ON commerce_membership_daily_reward (tenant_id, user_id, reward_date DESC);

-- 2. Privilege usage tracking table
CREATE TABLE IF NOT EXISTS commerce_membership_privilege_usage (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    user_id         INTEGER      NOT NULL,
    subscription_id INTEGER,
    benefit_code    TEXT         NOT NULL,
    period_start    TEXT         NOT NULL,
    period_end      TEXT         NOT NULL,
    used_count      INTEGER      NOT NULL DEFAULT 0,
    usage_limit     INTEGER      NOT NULL DEFAULT 0,
    last_used_at    TEXT,
    version         INTEGER      NOT NULL DEFAULT 0,
    created_at      TEXT         NOT NULL,
    updated_at      TEXT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_privilege_usage_uuid
    ON commerce_membership_privilege_usage (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_privilege_usage_unique
    ON commerce_membership_privilege_usage (tenant_id, user_id, benefit_code, period_start);
CREATE INDEX IF NOT EXISTS idx_priv_usage_user_period
    ON commerce_membership_privilege_usage (tenant_id, user_id, period_end);

-- 3. Membership change audit log (immutable)
CREATE TABLE IF NOT EXISTS commerce_membership_change_log (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    subscription_id INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    action          TEXT         NOT NULL,
    from_status     TEXT,
    to_status       TEXT,
    from_plan_id    TEXT,
    to_plan_id      TEXT,
    operator_id     INTEGER,
    operator_type   TEXT         DEFAULT 'system',
    reason          TEXT,
    metadata        TEXT,
    request_id      TEXT,
    created_at      TEXT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_change_log_uuid
    ON commerce_membership_change_log (uuid);
CREATE INDEX IF NOT EXISTS idx_change_log_subscription
    ON commerce_membership_change_log (subscription_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_change_log_tenant_user
    ON commerce_membership_change_log (tenant_id, user_id, created_at DESC);

-- folded migration: migrations/sqlite/0001_membership_extension_tables.up.sql
-- Membership extension tables migration (SQLite)
-- Adds membership-specific tables owned by sdkwork-membership capability.
-- Existing commerce domain tables are created by the commerce platform initial migration.

-- 1. Daily reward tracking table
CREATE TABLE IF NOT EXISTS commerce_membership_daily_reward (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    user_id         INTEGER      NOT NULL,
    reward_date     TEXT         NOT NULL,
    reward_points   INTEGER      NOT NULL DEFAULT 0,
    consecutive_days INTEGER     NOT NULL DEFAULT 1,
    total_days      INTEGER      NOT NULL DEFAULT 1,
    status          TEXT         NOT NULL DEFAULT 'claimed',
    idempotency_key TEXT,
    created_at      TEXT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_uuid
    ON commerce_membership_daily_reward (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_daily_reward_user_date
    ON commerce_membership_daily_reward (tenant_id, user_id, reward_date);
CREATE INDEX IF NOT EXISTS idx_daily_reward_user_recent
    ON commerce_membership_daily_reward (tenant_id, user_id, reward_date DESC);

-- 2. Privilege usage tracking table
CREATE TABLE IF NOT EXISTS commerce_membership_privilege_usage (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    user_id         INTEGER      NOT NULL,
    subscription_id INTEGER,
    benefit_code    TEXT         NOT NULL,
    period_start    TEXT         NOT NULL,
    period_end      TEXT         NOT NULL,
    used_count      INTEGER      NOT NULL DEFAULT 0,
    usage_limit     INTEGER      NOT NULL DEFAULT 0,
    last_used_at    TEXT,
    version         INTEGER      NOT NULL DEFAULT 0,
    created_at      TEXT         NOT NULL,
    updated_at      TEXT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_privilege_usage_uuid
    ON commerce_membership_privilege_usage (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_privilege_usage_unique
    ON commerce_membership_privilege_usage (tenant_id, user_id, benefit_code, period_start);
CREATE INDEX IF NOT EXISTS idx_priv_usage_user_period
    ON commerce_membership_privilege_usage (tenant_id, user_id, period_end);

-- 3. Membership change audit log (immutable)
CREATE TABLE IF NOT EXISTS commerce_membership_change_log (
    id              INTEGER      NOT NULL,
    uuid            TEXT         NOT NULL,
    tenant_id       INTEGER      NOT NULL,
    organization_id INTEGER      NOT NULL DEFAULT 0,
    subscription_id INTEGER      NOT NULL,
    user_id         INTEGER      NOT NULL,
    action          TEXT         NOT NULL,
    from_status     TEXT,
    to_status       TEXT,
    from_plan_id    TEXT,
    to_plan_id      TEXT,
    operator_id     INTEGER,
    operator_type   TEXT         DEFAULT 'system',
    reason          TEXT,
    metadata        TEXT,
    request_id      TEXT,
    created_at      TEXT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_commerce_membership_change_log_uuid
    ON commerce_membership_change_log (uuid);
CREATE INDEX IF NOT EXISTS idx_change_log_subscription
    ON commerce_membership_change_log (subscription_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_change_log_tenant_user
    ON commerce_membership_change_log (tenant_id, user_id, created_at DESC);

-- 4. Add missing standard columns to existing membership tables
-- SQLite does not support ADD COLUMN IF NOT EXISTS, so we use a pragma check approach.
-- These are safe to run repeatedly; SQLite will error on duplicate columns which we ignore.

-- Add uuid, version, deleted_at to membership_plan
-- Note: In SQLite, we cannot easily check column existence in pure SQL.
-- The application layer handles this gracefully via error tolerance.

-- Add tags column to membership_package if missing
-- This is handled by the application layer's read_model fallback.

-- 5. Performance indexes
CREATE INDEX IF NOT EXISTS idx_membership_plan_tenant_status_rank
    ON membership_plan (tenant_id, organization_id, status, rank);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_tenant_status_sort
    ON membership_package_group (tenant_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_status_sort
    ON membership_package (package_group_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_tenant_status
    ON membership_package (tenant_id, organization_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_subscription_owner_status
    ON membership_subscription (tenant_id, owner_user_id, status, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_membership_plan_benefit_version_status
    ON membership_plan_benefit (plan_version_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_entitlement_account_subject_status
    ON entitlement_account (tenant_id, subject_id, status);

CREATE INDEX IF NOT EXISTS idx_entitlement_grant_source
    ON entitlement_grant (source_type, source_id, status);

CREATE INDEX IF NOT EXISTS idx_entitlement_ledger_account
    ON entitlement_ledger_entry (account_id, occurred_at DESC);
