//! Generated gateway bootstrap for sdkwork-membership.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_membership_service_host::MembershipServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<MembershipServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_membership_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_membership_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}

pub async fn assemble_application_business_router_from_env() -> Result<ApplicationAssembly, String> {
    let host = Arc::new(MembershipServiceHost::from_env().await?);
    Ok(assemble_application_router(host).await)
}
