-- SDKWork membership consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_membership_baseline.sql
-- SDKWork membership consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_membership_baseline.sql
-- Membership initialization tables (PostgreSQL).
-- This repository is self-contained for local membership frontend/backend
-- integration. Order creation remains owned by sdkwork-order; this baseline
-- does not create commerce_order and seeds do not insert order rows.

-- 0. Local support tables required by membership catalog, entitlement, and
-- authenticated frontend flows.

CREATE TABLE IF NOT EXISTS membership_plan (
    id              TEXT NOT NULL,
    uuid            VARCHAR(64),
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    category        TEXT NOT NULL DEFAULT 'token',
    plan_no         TEXT NOT NULL,
    plan_code       TEXT,
    name            TEXT NOT NULL,
    rank            INTEGER NOT NULL DEFAULT 0,
    description     TEXT,
    sort_weight     INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'active',
    version         BIGINT NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_plan PRIMARY KEY (id),
    CONSTRAINT uk_membership_plan_tenant_no UNIQUE (tenant_id, organization_id, plan_no),
    CONSTRAINT ck_membership_plan_category CHECK (category IN ('token', 'community')),
    CONSTRAINT ck_membership_plan_status CHECK (status IN ('active', 'inactive', 'disabled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_uuid
    ON membership_plan (uuid);

CREATE TABLE IF NOT EXISTS membership_plan_version (
    id               TEXT NOT NULL,
    uuid             VARCHAR(64),
    tenant_id        TEXT NOT NULL,
    organization_id  TEXT NOT NULL DEFAULT '0',
    plan_id          TEXT NOT NULL,
    version_no       TEXT NOT NULL,
    title            TEXT,
    description      TEXT,
    lifecycle_status TEXT NOT NULL DEFAULT 'draft',
    effective_from   TIMESTAMPTZ,
    effective_to     TIMESTAMPTZ,
    published_at     TIMESTAMPTZ,
    version          BIGINT NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_plan_version PRIMARY KEY (id),
    CONSTRAINT uk_membership_plan_version_tenant_plan_no UNIQUE (tenant_id, plan_id, version_no),
    CONSTRAINT ck_membership_plan_version_lifecycle CHECK (lifecycle_status IN ('draft', 'published', 'archived'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_version_uuid
    ON membership_plan_version (uuid);
CREATE INDEX IF NOT EXISTS idx_membership_plan_version_published
    ON membership_plan_version (tenant_id, plan_id, lifecycle_status, version_no);

CREATE TABLE IF NOT EXISTS membership_benefit_definition (
    id               TEXT NOT NULL,
    uuid             VARCHAR(64),
    tenant_id        TEXT NOT NULL,
    organization_id  TEXT NOT NULL DEFAULT '0',
    benefit_code     TEXT NOT NULL,
    name             TEXT NOT NULL,
    benefit_type     TEXT NOT NULL,
    value_unit       TEXT,
    measurement_type TEXT,
    description      TEXT,
    status           TEXT NOT NULL DEFAULT 'active',
    version          BIGINT NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_benefit_definition PRIMARY KEY (id),
    CONSTRAINT uk_membership_benefit_definition_tenant_code UNIQUE (tenant_id, organization_id, benefit_code),
    CONSTRAINT ck_membership_benefit_definition_type CHECK (benefit_type IN ('points', 'feature', 'queue', 'quota', 'service'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_benefit_definition_uuid
    ON membership_benefit_definition (uuid);

CREATE TABLE IF NOT EXISTS membership_plan_benefit (
    id              TEXT NOT NULL,
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    plan_id         TEXT NOT NULL,
    plan_version_id TEXT NOT NULL,
    benefit_id      TEXT NOT NULL,
    benefit_code    TEXT NOT NULL,
    grant_quantity  TEXT NOT NULL DEFAULT '0',
    grant_period    TEXT,
    reset_policy    TEXT,
    usage_policy    TEXT,
    sort_weight     INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_plan_benefit PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_membership_plan_benefit_plan
    ON membership_plan_benefit (tenant_id, plan_id, status, sort_weight);

CREATE TABLE IF NOT EXISTS membership_package_group (
    id              TEXT NOT NULL,
    uuid            VARCHAR(64),
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    category        TEXT NOT NULL DEFAULT 'token',
    external_id     INTEGER,
    group_no        TEXT NOT NULL,
    name            TEXT NOT NULL,
    description     TEXT,
    billing_cycle   TEXT,
    duration_days   INTEGER NOT NULL DEFAULT 0,
    display_channel TEXT,
    sort_weight     INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'active',
    version         BIGINT NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_package_group PRIMARY KEY (id),
    CONSTRAINT uk_membership_package_group_tenant_no UNIQUE (tenant_id, organization_id, group_no),
    CONSTRAINT ck_membership_package_group_category CHECK (category IN ('token', 'community')),
    CONSTRAINT ck_membership_package_group_status CHECK (status IN ('active', 'inactive', 'disabled')),
    CONSTRAINT ck_membership_package_group_billing_cycle CHECK (billing_cycle IS NULL OR billing_cycle IN ('once', 'day', 'week', 'month', 'quarter', 'year')),
    CONSTRAINT ck_membership_package_group_display_channel CHECK (display_channel IS NULL OR display_channel IN ('app', 'pc', 'all'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_group_uuid
    ON membership_package_group (uuid);

CREATE TABLE IF NOT EXISTS membership_package (
    id                    TEXT NOT NULL,
    uuid                  VARCHAR(64),
    tenant_id             TEXT NOT NULL,
    organization_id       TEXT NOT NULL DEFAULT '0',
    category              TEXT NOT NULL DEFAULT 'token',
    external_id           INTEGER NOT NULL,
    package_no            TEXT NOT NULL,
    package_group_id      TEXT NOT NULL,
    plan_id               TEXT NOT NULL,
    plan_version_id       TEXT,
    sku_id                TEXT,
    name                  TEXT NOT NULL,
    description           TEXT,
    price_amount          TEXT NOT NULL,
    original_price_amount TEXT,
    currency_code         TEXT NOT NULL DEFAULT 'CNY',
    point_amount          INTEGER NOT NULL DEFAULT 0,
    discount              BIGINT NOT NULL DEFAULT 100,
    duration_days         INTEGER NOT NULL,
    recurrence_cycle      TEXT,
    sort_weight           INTEGER NOT NULL DEFAULT 0,
    recommended           INTEGER NOT NULL DEFAULT 0,
    status                TEXT NOT NULL DEFAULT 'active',
    starts_at             TIMESTAMPTZ,
    ends_at               TIMESTAMPTZ,
    tags                  JSONB NOT NULL DEFAULT '[]'::jsonb,
    version               BIGINT NOT NULL DEFAULT 0,
    deleted_at            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_package PRIMARY KEY (id),
    CONSTRAINT uk_membership_package_tenant_no UNIQUE (tenant_id, organization_id, package_no),
    CONSTRAINT ck_membership_package_discount_range CHECK (discount >= 1 AND discount <= 100),
    CONSTRAINT ck_membership_package_category CHECK (category IN ('token', 'community')),
    CONSTRAINT ck_membership_package_status CHECK (status IN ('active', 'inactive', 'disabled')),
    CONSTRAINT ck_membership_package_recurrence_cycle CHECK (recurrence_cycle IS NULL OR recurrence_cycle IN ('once', 'day', 'week', 'month', 'quarter', 'year'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_uuid
    ON membership_package (uuid);
CREATE INDEX IF NOT EXISTS idx_membership_package_external_id
    ON membership_package (tenant_id, organization_id, external_id);

CREATE TABLE IF NOT EXISTS membership_subscription (
    id                       TEXT NOT NULL,
    uuid                     VARCHAR(64),
    tenant_id                TEXT NOT NULL,
    organization_id          TEXT NOT NULL DEFAULT '0',
    category                 TEXT NOT NULL DEFAULT 'token',
    subscription_no          TEXT NOT NULL,
    subject_type             TEXT NOT NULL,
    subject_id               TEXT NOT NULL,
    owner_user_id            TEXT NOT NULL,
    plan_id                  TEXT NOT NULL,
    plan_version_id          TEXT,
    package_id               TEXT,
    current_period_id        TEXT,
    source_order_id          TEXT,
    status                   TEXT NOT NULL DEFAULT 'pending',
    starts_at                TIMESTAMPTZ NOT NULL,
    expires_at               TIMESTAMPTZ NOT NULL,
    grace_until              TIMESTAMPTZ,
    cancel_at_period_end     INTEGER NOT NULL DEFAULT 0,
    auto_renew               INTEGER NOT NULL DEFAULT 0,
    growth_value             BIGINT NOT NULL DEFAULT 0,
    request_no               TEXT,
    idempotency_key          TEXT,
    version                  BIGINT NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_subscription PRIMARY KEY (id),
    CONSTRAINT ck_membership_subscription_category CHECK (category IN ('token', 'community')),
    CONSTRAINT ck_membership_subscription_status CHECK (status IN ('pending', 'pending_activation', 'active', 'grace_period', 'expired', 'cancelled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_subscription_uuid
    ON membership_subscription (uuid);
CREATE INDEX IF NOT EXISTS idx_membership_subscription_idempotency
    ON membership_subscription (tenant_id, owner_user_id, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_membership_subscription_order
    ON membership_subscription (tenant_id, source_order_id);

CREATE TABLE IF NOT EXISTS membership_period (
    id                       TEXT NOT NULL,
    uuid                     VARCHAR(64),
    tenant_id                TEXT NOT NULL,
    organization_id          TEXT NOT NULL DEFAULT '0',
    category                 TEXT NOT NULL DEFAULT 'token',
    period_no                TEXT NOT NULL,
    subscription_id          TEXT NOT NULL,
    subject_type             TEXT NOT NULL,
    subject_id               TEXT NOT NULL,
    plan_id                  TEXT NOT NULL,
    plan_version_id          TEXT,
    starts_at                TIMESTAMPTZ NOT NULL,
    ends_at                  TIMESTAMPTZ NOT NULL,
    status                   TEXT NOT NULL,
    source_order_id          TEXT,
    request_no               TEXT,
    idempotency_key          TEXT,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_period PRIMARY KEY (id),
    CONSTRAINT ck_membership_period_category CHECK (category IN ('token', 'community')),
    CONSTRAINT ck_membership_period_status CHECK (status IN ('pending', 'pending_activation', 'active', 'expired', 'cancelled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_period_uuid
    ON membership_period (uuid);
CREATE INDEX IF NOT EXISTS idx_membership_period_subscription
    ON membership_period (tenant_id, subscription_id, starts_at);

CREATE TABLE IF NOT EXISTS membership_entitlement_account (
    id              TEXT NOT NULL,
    uuid            VARCHAR(64),
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    account_no      TEXT NOT NULL,
    benefit_id      TEXT NOT NULL,
    subject_type    TEXT NOT NULL,
    subject_id      TEXT NOT NULL,
    total_granted   TEXT NOT NULL DEFAULT '0',
    total_used      TEXT NOT NULL DEFAULT '0',
    balance         TEXT NOT NULL DEFAULT '0',
    status          TEXT NOT NULL DEFAULT 'pending',
    expires_at      TIMESTAMPTZ,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_entitlement_account PRIMARY KEY (id),
    CONSTRAINT uk_membership_entitlement_account_subject_benefit UNIQUE (tenant_id, subject_type, subject_id, benefit_id),
    CONSTRAINT ck_membership_entitlement_account_status CHECK (status IN ('pending', 'active', 'expired', 'cancelled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_entitlement_account_uuid
    ON membership_entitlement_account (uuid);

CREATE TABLE IF NOT EXISTS membership_entitlement_grant (
    id               TEXT NOT NULL,
    uuid             VARCHAR(64),
    tenant_id        TEXT NOT NULL,
    organization_id  TEXT NOT NULL DEFAULT '0',
    grant_no         TEXT NOT NULL,
    benefit_id       TEXT NOT NULL,
    subject_type     TEXT NOT NULL,
    subject_id       TEXT NOT NULL,
    source_type      TEXT NOT NULL,
    source_id        TEXT NOT NULL,
    grant_policy     TEXT,
    granted_quantity TEXT NOT NULL DEFAULT '0',
    status           TEXT NOT NULL DEFAULT 'pending',
    starts_at        TIMESTAMPTZ,
    expires_at       TIMESTAMPTZ,
    request_no       TEXT,
    idempotency_key  TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_entitlement_grant PRIMARY KEY (id),
    CONSTRAINT ck_membership_entitlement_grant_status CHECK (status IN ('pending', 'active', 'expired', 'cancelled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_entitlement_grant_uuid
    ON membership_entitlement_grant (uuid);

CREATE TABLE IF NOT EXISTS membership_entitlement_ledger_entry (
    id              TEXT NOT NULL,
    uuid            VARCHAR(64),
    tenant_id       TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    ledger_no       TEXT NOT NULL,
    account_id      TEXT NOT NULL,
    grant_id        TEXT,
    benefit_id      TEXT NOT NULL,
    subject_type    TEXT NOT NULL,
    subject_id      TEXT NOT NULL,
    direction       TEXT NOT NULL,
    amount          TEXT NOT NULL,
    balance_after   TEXT NOT NULL,
    business_type   TEXT NOT NULL,
    source_type     TEXT NOT NULL,
    source_id       TEXT NOT NULL,
    request_no      TEXT,
    idempotency_key TEXT,
    occurred_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_entitlement_ledger_entry PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_entitlement_ledger_uuid
    ON membership_entitlement_ledger_entry (uuid);

CREATE TABLE IF NOT EXISTS membership_points_account (
    id               BIGINT NOT NULL,
    uuid             VARCHAR(64) NOT NULL,
    tenant_id        BIGINT NOT NULL,
    organization_id  BIGINT NOT NULL DEFAULT 0,
    owner_type       VARCHAR(32) NOT NULL DEFAULT 'USER',
    owner_id         BIGINT NOT NULL,
    asset_code       VARCHAR(32) NOT NULL,
    currency_code    VARCHAR(16) NOT NULL,
    account_purpose  VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
    available_amount BIGINT NOT NULL DEFAULT 0,
    frozen_amount    BIGINT NOT NULL DEFAULT 0,
    pending_amount   BIGINT NOT NULL DEFAULT 0,
    status           INTEGER NOT NULL DEFAULT 1,
    version          BIGINT NOT NULL DEFAULT 0,
    closed_at        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_points_account PRIMARY KEY (id),
    CONSTRAINT uk_membership_points_account_uuid UNIQUE (uuid),
    CONSTRAINT uk_membership_points_account_owner_asset UNIQUE (
        tenant_id, organization_id, owner_type, owner_id,
        asset_code, currency_code, account_purpose
    )
);

CREATE INDEX IF NOT EXISTS idx_membership_points_account_tenant_owner
    ON membership_points_account (tenant_id, organization_id, owner_type, owner_id, asset_code);

-- Ensure all membership_points_account columns exist on tables created by older baseline revisions.
ALTER TABLE membership_points_account ADD COLUMN IF NOT EXISTS uuid VARCHAR(64);
ALTER TABLE membership_points_account ADD COLUMN IF NOT EXISTS owner_type VARCHAR(32) NOT NULL DEFAULT 'USER';
ALTER TABLE membership_points_account ADD COLUMN IF NOT EXISTS account_purpose VARCHAR(32) NOT NULL DEFAULT 'GENERAL';
ALTER TABLE membership_points_account ADD COLUMN IF NOT EXISTS pending_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE membership_points_account ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS membership_points_ledger (
    id                     BIGINT NOT NULL,
    uuid                   VARCHAR(64) NOT NULL,
    tenant_id              BIGINT NOT NULL,
    organization_id        BIGINT NOT NULL DEFAULT 0,
    account_id             BIGINT NOT NULL,
    journal_id             BIGINT,
    owner_type             VARCHAR(32) NOT NULL,
    owner_id               BIGINT NOT NULL,
    asset_code             VARCHAR(32) NOT NULL,
    currency_code          VARCHAR(16) NOT NULL,
    ledger_type            VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    entry_type             VARCHAR(32) NOT NULL,
    direction              VARCHAR(16) NOT NULL,
    amount                 BIGINT NOT NULL,
    balance_before         BIGINT NOT NULL,
    balance_after          BIGINT NOT NULL,
    business_type          VARCHAR(64) NOT NULL,
    business_no            VARCHAR(128) NOT NULL,
    request_no             VARCHAR(128) NOT NULL,
    idempotency_key        VARCHAR(200) NOT NULL,
    source_type            VARCHAR(64),
    source_id              BIGINT,
    hold_id                BIGINT,
    transfer_id            BIGINT,
    exchange_snapshot_id   BIGINT,
    settlement_snapshot_id BIGINT,
    reversed_ledger_id     BIGINT,
    reference_no           VARCHAR(128),
    remark                 VARCHAR(512),
    metadata_json          JSONB NOT NULL DEFAULT '{}'::jsonb,
    trace_id               VARCHAR(128) NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_membership_points_ledger PRIMARY KEY (id),
    CONSTRAINT uk_membership_points_ledger_uuid UNIQUE (uuid),
    CONSTRAINT uk_membership_points_ledger_business_no UNIQUE (tenant_id, business_no),
    CONSTRAINT uk_membership_points_ledger_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_membership_points_ledger_account_created
    ON membership_points_ledger (tenant_id, account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_membership_points_ledger_owner_created
    ON membership_points_ledger (tenant_id, organization_id, owner_type, owner_id, asset_code, created_at DESC);

-- Ensure all membership_points_ledger columns exist on tables created by older baseline revisions.
-- PostgreSQL idempotent table creation does not modify an existing table, so columns added in later
-- revisions must be back-filled with ALTER TABLE ADD COLUMN IF NOT EXISTS.
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS journal_id BIGINT;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS ledger_type VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS hold_id BIGINT;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS transfer_id BIGINT;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS exchange_snapshot_id BIGINT;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS settlement_snapshot_id BIGINT;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS reversed_ledger_id BIGINT;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS reference_no VARCHAR(128);
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE membership_points_ledger ADD COLUMN IF NOT EXISTS trace_id VARCHAR(128) NOT NULL DEFAULT '';

-- 1. Daily reward tracking table
CREATE TABLE IF NOT EXISTS membership_daily_reward (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT       NOT NULL,
    reward_date     DATE         NOT NULL,
    reward_points   BIGINT       NOT NULL DEFAULT 0,
    consecutive_days INTEGER     NOT NULL DEFAULT 1,
    total_days      INTEGER      NOT NULL DEFAULT 1,
    status          VARCHAR(32)  NOT NULL DEFAULT 'claimed',
    idempotency_key VARCHAR(64),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version         BIGINT       NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_membership_daily_reward PRIMARY KEY (id),
    CONSTRAINT uk_membership_daily_reward_uuid UNIQUE (uuid),
    CONSTRAINT uk_membership_daily_reward_user_date UNIQUE (tenant_id, user_id, reward_date),
    CONSTRAINT uk_membership_daily_reward_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_daily_reward_points CHECK (reward_points >= 0),
    CONSTRAINT chk_daily_reward_consecutive CHECK (consecutive_days >= 1),
    CONSTRAINT chk_daily_reward_status CHECK (status IN ('claimed', 'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_daily_reward_user_recent
    ON membership_daily_reward (tenant_id, user_id, reward_date DESC, id DESC);

-- Ensure daily_reward columns added in later baseline revisions exist on older tables.
ALTER TABLE membership_daily_reward ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE membership_daily_reward ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 2. Privilege usage tracking table
CREATE TABLE IF NOT EXISTS membership_privilege_usage (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT       NOT NULL,
    subscription_id BIGINT,
    benefit_code    VARCHAR(64)  NOT NULL,
    period_start    TIMESTAMPTZ  NOT NULL,
    period_end      TIMESTAMPTZ  NOT NULL,
    used_count      BIGINT       NOT NULL DEFAULT 0,
    usage_limit     BIGINT       NOT NULL DEFAULT 0,
    last_used_at    TIMESTAMPTZ,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_membership_privilege_usage PRIMARY KEY (id),
    CONSTRAINT uk_membership_privilege_usage_uuid UNIQUE (uuid),
    CONSTRAINT uk_membership_privilege_usage_unique UNIQUE (tenant_id, user_id, benefit_code, period_start),
    CONSTRAINT chk_priv_usage_used CHECK (used_count >= 0),
    CONSTRAINT chk_priv_usage_limit CHECK (usage_limit >= 0),
    CONSTRAINT chk_priv_usage_period CHECK (period_end >= period_start)
);

CREATE INDEX IF NOT EXISTS idx_priv_usage_user_period
    ON membership_privilege_usage (tenant_id, user_id, period_end);
CREATE INDEX IF NOT EXISTS idx_priv_usage_subscription
    ON membership_privilege_usage (subscription_id, created_at DESC);

-- 3. Membership change audit log (immutable)
CREATE TABLE IF NOT EXISTS membership_change_log (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    subscription_id BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    action          VARCHAR(64)  NOT NULL,
    from_status     VARCHAR(32),
    to_status       VARCHAR(32),
    from_plan_id    VARCHAR(128),
    to_plan_id      VARCHAR(128),
    operator_id     BIGINT,
    operator_type   VARCHAR(32)  DEFAULT 'system',
    reason          VARCHAR(256),
    metadata        JSONB,
    trace_id        VARCHAR(64),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_membership_change_log PRIMARY KEY (id),
    CONSTRAINT uk_membership_change_log_uuid UNIQUE (uuid),
    CONSTRAINT chk_change_log_action CHECK (action IN (
        'activate', 'renew', 'upgrade', 'downgrade',
        'expire', 'cancel', 'grace', 'restore'
    )),
    CONSTRAINT chk_change_log_from_status CHECK (from_status IS NULL OR from_status IN ('active', 'expired', 'cancelled', 'grace_period', 'pending')),
    CONSTRAINT chk_change_log_to_status CHECK (to_status IS NULL OR to_status IN ('active', 'expired', 'cancelled', 'grace_period', 'pending'))
);

CREATE INDEX IF NOT EXISTS idx_change_log_subscription
    ON membership_change_log (subscription_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_change_log_tenant_user
    ON membership_change_log (tenant_id, user_id, created_at DESC, id DESC);

-- 4. Add missing standard columns to existing membership tables
-- These ALTER TABLE statements are idempotent via DO blocks.

-- Add uuid column to membership_plan
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_plan' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_plan ADD COLUMN uuid VARCHAR(64);
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_uuid ON membership_plan (uuid);
    END IF;
END $$;

-- Add version column to membership_plan
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_plan' AND column_name = 'version'
    ) THEN
        ALTER TABLE membership_plan ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
    END IF;
END $$;

-- Add deleted_at column to membership_plan
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_plan' AND column_name = 'deleted_at'
    ) THEN
        ALTER TABLE membership_plan ADD COLUMN deleted_at TIMESTAMPTZ;
    END IF;
END $$;

-- Add uuid, version, deleted_at to membership_package_group
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_package_group' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_package_group ADD COLUMN uuid VARCHAR(64);
        ALTER TABLE membership_package_group ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
        ALTER TABLE membership_package_group ADD COLUMN deleted_at TIMESTAMPTZ;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_group_uuid ON membership_package_group (uuid);
    END IF;
END $$;

-- Add uuid, version, deleted_at to membership_package
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_package' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_package ADD COLUMN uuid VARCHAR(64);
        ALTER TABLE membership_package ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
        ALTER TABLE membership_package ADD COLUMN deleted_at TIMESTAMPTZ;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_package_uuid ON membership_package (uuid);
    END IF;
END $$;

-- Add tags column to membership_package if missing
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_package' AND column_name = 'tags'
    ) THEN
        ALTER TABLE membership_package ADD COLUMN tags JSONB NOT NULL DEFAULT '[]'::jsonb;
    END IF;
END $$;

-- Add discount column to membership_package if missing (100 = no discount)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_package' AND column_name = 'discount'
    ) THEN
        ALTER TABLE membership_package ADD COLUMN discount BIGINT NOT NULL DEFAULT 100;
        ALTER TABLE membership_package
            ADD CONSTRAINT ck_membership_package_discount_range
            CHECK (discount >= 1 AND discount <= 100);
    END IF;
END $$;

-- Add uuid, version to membership_subscription
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_subscription' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_subscription ADD COLUMN uuid VARCHAR(64);
        ALTER TABLE membership_subscription ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
        ALTER TABLE membership_subscription ADD COLUMN auto_renew BOOLEAN NOT NULL DEFAULT FALSE;
        ALTER TABLE membership_subscription ADD COLUMN growth_value BIGINT NOT NULL DEFAULT 0;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_subscription_uuid ON membership_subscription (uuid);
    END IF;
END $$;

-- Add uuid to membership_period
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_period' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_period ADD COLUMN uuid VARCHAR(64);
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_period_uuid ON membership_period (uuid);
    END IF;
END $$;

-- Add uuid to membership_plan_version
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_plan_version' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_plan_version ADD COLUMN uuid VARCHAR(64);
        ALTER TABLE membership_plan_version ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_plan_version_uuid ON membership_plan_version (uuid);
    END IF;
END $$;

-- Add uuid to membership_benefit_definition
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_benefit_definition' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_benefit_definition ADD COLUMN uuid VARCHAR(64);
        ALTER TABLE membership_benefit_definition ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_benefit_definition_uuid ON membership_benefit_definition (uuid);
    END IF;
END $$;

-- Add uuid to membership_entitlement_account
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_entitlement_account' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_entitlement_account ADD COLUMN uuid VARCHAR(64);
        ALTER TABLE membership_entitlement_account ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_entitlement_account_uuid ON membership_entitlement_account (uuid);
    END IF;
END $$;

-- Add uuid to membership_entitlement_grant
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_entitlement_grant' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_entitlement_grant ADD COLUMN uuid VARCHAR(64);
        CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_entitlement_grant_uuid ON membership_entitlement_grant (uuid);
    END IF;
END $$;

-- Add uuid to membership_entitlement_ledger_entry
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'membership_entitlement_ledger_entry' AND column_name = 'uuid'
    ) THEN
        ALTER TABLE membership_entitlement_ledger_entry ADD COLUMN uuid VARCHAR(64);
        CREATE UNIQUE INDEX IF NOT EXISTS uk_entitlement_ledger_uuid ON membership_entitlement_ledger_entry (uuid);
    END IF;
END $$;

-- 5. Add performance indexes for high-frequency queries
CREATE INDEX IF NOT EXISTS idx_membership_plan_tenant_status_rank
    ON membership_plan (tenant_id, organization_id, status, rank);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_tenant_status_sort
    ON membership_package_group (tenant_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_status_sort
    ON membership_package (package_group_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_tenant_status
    ON membership_package (tenant_id, organization_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_subscription_owner_status
    ON membership_subscription (tenant_id, owner_user_id, status, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_membership_subscription_expire
    ON membership_subscription (status, expires_at)
    WHERE status IN ('active', 'grace_period');

CREATE INDEX IF NOT EXISTS idx_membership_plan_benefit_version_status
    ON membership_plan_benefit (plan_version_id, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_entitlement_account_subject_status
    ON membership_entitlement_account (tenant_id, subject_id, status);

CREATE INDEX IF NOT EXISTS idx_membership_entitlement_grant_source
    ON membership_entitlement_grant (source_type, source_id, status);

CREATE INDEX IF NOT EXISTS idx_membership_entitlement_grant_expire
    ON membership_entitlement_grant (status, expires_at)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_entitlement_ledger_account
    ON membership_entitlement_ledger_entry (account_id, occurred_at DESC);

-- 5b. Category-aware catalog and entitlement indexes
CREATE INDEX IF NOT EXISTS idx_membership_plan_tenant_category
    ON membership_plan (tenant_id, organization_id, category, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_tenant_category
    ON membership_package_group (tenant_id, organization_id, category, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_tenant_category
    ON membership_package (tenant_id, organization_id, category, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_subscription_tenant_category
    ON membership_subscription (tenant_id, organization_id, category, status, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_membership_period_tenant_category
    ON membership_period (tenant_id, organization_id, category, status, ends_at DESC);

-- 6. updated_at maintenance triggers for membership-owned mutable tables
CREATE OR REPLACE FUNCTION fn_membership_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_membership_priv_usage_updated ON membership_privilege_usage;
CREATE TRIGGER trg_membership_priv_usage_updated
    BEFORE UPDATE ON membership_privilege_usage
    FOR EACH ROW EXECUTE FUNCTION fn_membership_set_updated_at();

DROP TRIGGER IF EXISTS trg_membership_daily_reward_updated ON membership_daily_reward;
CREATE TRIGGER trg_membership_daily_reward_updated
    BEFORE UPDATE ON membership_daily_reward
    FOR EACH ROW EXECUTE FUNCTION fn_membership_set_updated_at();

-- folded migration: migrations/postgres/0002_change_log_text_ids.up.sql
-- sdkwork:migration
-- id: 0002_change_log_text_ids
-- engine: postgres
-- module: membership
-- purpose: align membership_change_log id columns with the TEXT id scheme used by membership_subscription and sibling tables
-- reversible: true
-- transactional: true

-- membership_change_log is unused legacy scaffolding; converting its BIGINT id
-- columns to TEXT makes it usable with the TEXT-id domain (subscription/tenant/user).

ALTER TABLE membership_change_log
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN tenant_id DROP DEFAULT,
    ALTER COLUMN organization_id DROP DEFAULT,
    ALTER COLUMN id TYPE TEXT USING id::TEXT,
    ALTER COLUMN tenant_id TYPE TEXT USING tenant_id::TEXT,
    ALTER COLUMN organization_id TYPE TEXT USING organization_id::TEXT,
    ALTER COLUMN subscription_id TYPE TEXT USING subscription_id::TEXT,
    ALTER COLUMN user_id TYPE TEXT USING user_id::TEXT,
    ALTER COLUMN operator_id TYPE TEXT USING operator_id::TEXT;

-- folded migration: migrations/postgres/0003_membership_category.up.sql
-- sdkwork:migration
-- id: 0003_membership_category
-- engine: postgres
-- module: sdkwork-membership
-- purpose: Introduce the membership category classification dimension
--   (token plans, community/circle plans, future extensions) on plan,
--   package group, package, subscription, and period, and enforce the
--   catalog enum vocabulary with CHECK constraints (status, billing and
--   recurrence cycles, display channel, benefit type). Existing rows are
--   backfilled to category 'token' (all pre-standard catalog data is
--   token-plan data); subscription and period categories are snapshotted
--   from their plan at write time by the application layer.
-- reversible: true
-- transactional: true

-- 1. Category dimension (extensible enum: token | community | future values)
ALTER TABLE membership_plan
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'token';
ALTER TABLE membership_plan
    ADD COLUMN IF NOT EXISTS sort_weight INTEGER NOT NULL DEFAULT 0;
ALTER TABLE membership_plan
    DROP CONSTRAINT IF EXISTS ck_membership_plan_category;
ALTER TABLE membership_plan
    ADD CONSTRAINT ck_membership_plan_category
    CHECK (category IN ('token', 'community'));

ALTER TABLE membership_package_group
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'token';
ALTER TABLE membership_package_group
    DROP CONSTRAINT IF EXISTS ck_membership_package_group_category;
ALTER TABLE membership_package_group
    ADD CONSTRAINT ck_membership_package_group_category
    CHECK (category IN ('token', 'community'));

ALTER TABLE membership_package
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'token';
ALTER TABLE membership_package
    DROP CONSTRAINT IF EXISTS ck_membership_package_category;
ALTER TABLE membership_package
    ADD CONSTRAINT ck_membership_package_category
    CHECK (category IN ('token', 'community'));

ALTER TABLE membership_subscription
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'token';
ALTER TABLE membership_subscription
    DROP CONSTRAINT IF EXISTS ck_membership_subscription_category;
ALTER TABLE membership_subscription
    ADD CONSTRAINT ck_membership_subscription_category
    CHECK (category IN ('token', 'community'));

ALTER TABLE membership_period
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'token';
ALTER TABLE membership_period
    DROP CONSTRAINT IF EXISTS ck_membership_period_category;
ALTER TABLE membership_period
    ADD CONSTRAINT ck_membership_period_category
    CHECK (category IN ('token', 'community'));

-- 2. Catalog lifecycle status vocabulary (active | inactive | disabled)
ALTER TABLE membership_plan
    DROP CONSTRAINT IF EXISTS ck_membership_plan_status;
ALTER TABLE membership_plan
    ADD CONSTRAINT ck_membership_plan_status
    CHECK (status IN ('active', 'inactive', 'disabled'));

ALTER TABLE membership_package_group
    DROP CONSTRAINT IF EXISTS ck_membership_package_group_status;
ALTER TABLE membership_package_group
    ADD CONSTRAINT ck_membership_package_group_status
    CHECK (status IN ('active', 'inactive', 'disabled'));

ALTER TABLE membership_package
    DROP CONSTRAINT IF EXISTS ck_membership_package_status;
ALTER TABLE membership_package
    ADD CONSTRAINT ck_membership_package_status
    CHECK (status IN ('active', 'inactive', 'disabled'));

ALTER TABLE membership_plan_version
    DROP CONSTRAINT IF EXISTS ck_membership_plan_version_lifecycle;
ALTER TABLE membership_plan_version
    ADD CONSTRAINT ck_membership_plan_version_lifecycle
    CHECK (lifecycle_status IN ('draft', 'published', 'archived'));

-- 3. Billing / recurrence cycle vocabulary (once | day | week | month | quarter | year)
ALTER TABLE membership_package_group
    DROP CONSTRAINT IF EXISTS ck_membership_package_group_billing_cycle;
ALTER TABLE membership_package_group
    ADD CONSTRAINT ck_membership_package_group_billing_cycle
    CHECK (billing_cycle IN ('once', 'day', 'week', 'month', 'quarter', 'year'));

ALTER TABLE membership_package
    DROP CONSTRAINT IF EXISTS ck_membership_package_recurrence_cycle;
ALTER TABLE membership_package
    ADD CONSTRAINT ck_membership_package_recurrence_cycle
    CHECK (recurrence_cycle IN ('once', 'day', 'week', 'month', 'quarter', 'year'));

-- 4. Display channel and benefit type vocabulary
ALTER TABLE membership_package_group
    DROP CONSTRAINT IF EXISTS ck_membership_package_group_display_channel;
ALTER TABLE membership_package_group
    ADD CONSTRAINT ck_membership_package_group_display_channel
    CHECK (display_channel IS NULL OR display_channel IN ('app', 'pc', 'all'));

ALTER TABLE membership_benefit_definition
    DROP CONSTRAINT IF EXISTS ck_membership_benefit_definition_type;
ALTER TABLE membership_benefit_definition
    ADD CONSTRAINT ck_membership_benefit_definition_type
    CHECK (benefit_type IN ('points', 'feature', 'queue', 'quota', 'service'));

-- 5. Subscription / period status vocabulary
ALTER TABLE membership_subscription
    DROP CONSTRAINT IF EXISTS ck_membership_subscription_status;
ALTER TABLE membership_subscription
    ADD CONSTRAINT ck_membership_subscription_status
    CHECK (status IN ('pending', 'pending_activation', 'active', 'grace_period', 'expired', 'cancelled'));

ALTER TABLE membership_period
    DROP CONSTRAINT IF EXISTS ck_membership_period_status;
ALTER TABLE membership_period
    ADD CONSTRAINT ck_membership_period_status
    CHECK (status IN ('pending', 'pending_activation', 'active', 'expired', 'cancelled'));

ALTER TABLE membership_entitlement_account
    DROP CONSTRAINT IF EXISTS ck_membership_entitlement_account_status;
ALTER TABLE membership_entitlement_account
    ADD CONSTRAINT ck_membership_entitlement_account_status
    CHECK (status IN ('pending', 'active', 'expired', 'cancelled'));

ALTER TABLE membership_entitlement_grant
    DROP CONSTRAINT IF EXISTS ck_membership_entitlement_grant_status;
ALTER TABLE membership_entitlement_grant
    ADD CONSTRAINT ck_membership_entitlement_grant_status
    CHECK (status IN ('pending', 'active', 'expired', 'cancelled'));

-- 6. Category-aware catalog and entitlement indexes
CREATE INDEX IF NOT EXISTS idx_membership_plan_tenant_category
    ON membership_plan (tenant_id, organization_id, category, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_group_tenant_category
    ON membership_package_group (tenant_id, organization_id, category, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_package_tenant_category
    ON membership_package (tenant_id, organization_id, category, status, sort_weight);

CREATE INDEX IF NOT EXISTS idx_membership_subscription_tenant_category
    ON membership_subscription (tenant_id, organization_id, category, status, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_membership_period_tenant_category
    ON membership_period (tenant_id, organization_id, category, status, ends_at DESC);
